openapi: 3.0.3
info:
  title: User Registration API
  description: RESTful API for user registration and user details fetching using Spring Boot
  version: 1.0.0
paths:
  /api/user/register:
    post:
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '200':
          description: User registered successfully
        '500':
          description: User registration failed
  /api/user/fetch:
    get:
      summary: Fetch user details by username
      operationId: fetchUser
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User details fetched successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
                required:
                  - username
                  - email
        '404':
          description: User not found
        '500':
          description: Failed to fetch user details
